package lk.tideline.cleanup.model;

public enum AlertType {
    NEW_REPORT_NEARBY,
    REPORT_VERIFIED,
    ALERT_ESCALATED,
    PROJECT_PLANNED,
    PROJECT_UPDATE,
    AUTHORITY_DECISION,
    OPPORTUNITY,
    ACCOUNT_REVIEW,
    COMMENT_REPLY,
    INFO_REQUESTED,
    INFO_RESPONSE,
    RESOURCES_NEEDED,
    RESOURCES_ASSIGNED
}
